---

- name: Install Pleora SDK
  shell: "{{ installer_staging }}/pleora_setup/install.sh >> /tmp/pleora_install.log"
  args:
    chdir: "{{ installer_staging }}"
    executable: /bin/bash
    creates: pleora_install.log
  become: yes

- name: Tweak network settings
  shell: "{{ installer_staging }}/pleora_setup/bin/set_socket_buffer_size.sh >> /tmp/pleora_install.log"
  args:
    chdir: "{{ installer_staging }}/pleora_setup/bin"
    executable: /bin/bash
  become: yes

- name: Set the environment variables globally
  copy:
    src: /opt/pleora/ebus_sdk/Ubuntu-14.04-x86_64/bin/set_puregev_env
    dest: /etc/profile.d/pleora_envs.sh
    remote_src: yes
    force: yes
  become: yes
